#  $Id: GNUmakefile,v 1.2 2011/07/06 05:18:18 kelsey Exp $
#
#  Top-level makefile for building CDMS sources simulations
#  --------------------------------------------------------

ifneq (,$(CDMS_RDM_COLLIMATION))
  CPPFLAGS = -DCDMS_RDM_COLLIMATION
endif

# No subdirectories, no test executable (yet)

include build.gmk
