#  $Id: GNUmakefile,v 1.1 2010/12/23 16:48:42 kelsey Exp $
#
#  Top-level makefile for building CDMS GEANT4 base classes
#  --------------------------------------------------------

# No subdirectories, no test executable (yet)

include build.gmk
