#  $Id: GNUmakefile,v 1.4 2010/08/02 04:48:46 kelsey Exp $
#
#  Top-level makefile for building CDMS sources simulations
#  --------------------------------------------------------

# No subdirectories, no test executable (yet)

# CDMSSimRoot uses ROOT classes

CPPFLAGS += -I$(ROOTSYS)/include

include build.gmk
