# $Id: GNUmakefile,v 1.1 2010/10/28 04:36:21 kelsey Exp $
#
# --------------------------------------------------------------
# GNUmakefile for interface package    .  Michael Kelsey 26 October 2010
# --------------------------------------------------------------

CPPFLAGS += -I$(G4BASE)/global/management/include \
            -I$(G4BASE)/global/HEPGeometry/include \
            -I$(G4BASE)/intercoms/include \
            -I$(G4BASE)/run/include \
            -I$(G4BASE)/geometry/management/include \
            -I$(G4BASE)/geometry/solids/CSG/include \
            -I$(G4BASE)/geometry/volumes/include \
            -I$(G4BASE)/materials/include \
            -I$(G4BASE)/graphics_reps/include

include build.gmk
