# $Id: 7TowerSnoCosmic.mac,v 1.2 2011/07/22 19:35:06 kelsey Exp $
# Seven towers in cryostat with shielding in SNOLab cavern
# with cosmogenic source
#
/control/verbose 2
/run/verbose 2
/CDMS/verbose 0

# Configure lab
/CDMS/Lab SnoLab
/CDMS/SnoLabGeom/setOverBurden 5 m

# Configure detector (also defines subsequent commands)
/CDMS/Detector 100kg
/CDMS/UseShield
/CDMS/Shield/SidePanels 8
/CDMS/Layout/Code ring
/CDMS/Layout/Towers 1

# Add cosmogenic source
/CDMS/Source cosmu

### NOTE:  Must do this after configuration above
/CDMS/updateGeom

### NOTE: generator commands must go after geometry update
/CDMS/Cosmics/depth 1700 m
### NOTE: default energy range is 1 to 3001 GeV in 1000 bins
# /CDMS/Cosmics/energyRange 1 101 100

/vis/open OGL 600x600-0+0
/vis/verbose errors
/vis/viewer/set/autoRefresh false
/vis/viewer/set/upVector 0 0 1

/vis/viewer/set/viewpointVector 0 -1 0
/vis/viewer/addCutawayPlane 0 0 0 cm 0 1 0
/vis/drawVolume

/vis/scene/add/trajectories
/vis/filtering/trajectories/create/particleFilter
/vis/filtering/trajectories/particleFilter-0/add mu+
/vis/filtering/trajectories/particleFilter-0/add mu-
/vis/filtering/trajectories/particleFilter-0/add neutron

/vis/scene/endOfEventAction accumulate
/vis/viewer/set/autoRefresh true

# 
# 1000 events
#
/run/beamOn 1000
