
# This is a general macro for testing features of the
# RICOCHET/REvOLT-0 Monte Carlo v0.1 (RMC)
#
# Adam Anderson
# adama@mit.edu
#

#/control/verbose 2
#/run/verbose 2
#/CDMS/verbose 3

# Configure detector (also defines subsequent commands)
#/CDMS/Lab MITReactor
#/CDMS/Detector 100kg
#/CDMS/Layout/Towers 1
#/CDMS/UseShield
#/vis/scene/endOfEventAction accumulate
#/vis/viewer/set/autoRefresh true

#/CDMS/Source cosmu

### NOTE:  Must do this after configuration above
#/CDMS/updateGeom

#/CDMS/Cosmics/depth 1700

#/vis/open OGLIX 600x600-0+0
#/vis/verbose errors
#/vis/viewer/set/autoRefresh false
#/vis/viewer/set/upVector 0 0 1

#/vis/viewer/set/viewpointThetaPhi 85 270		# Slightly tilted
#/vis/viewer/addCutawayPlane 0 0 0 cm 0 1 0
#/vis/drawVolume
#/vis/viewer/flush
#/vis/ogl/printEPS

#/tracking/verbose 1
#/run/beamOn 10

#/control/verbose 0
#/run/verbose 0
#/CDMS/verbose 0

# Configure lab
/CDMS/Lab MITReactor
#/CDMS/SnoLabGeom/setOverBurden 5 m

# Configure detector (also defines subsequent commands)
/CDMS/Detector 100kg
/CDMS/UseShield
/CDMS/Layout/Towers 1

# Add cosmogenic source
/CDMS/Source cosmu

### NOTE:  Must do this after configuration above
/CDMS/updateGeom

#/vis/open OGL 600x600-0+0
#/vis/verbose errors
#/vis/viewer/set/autoRefresh false
#/vis/viewer/set/upVector 0 0 1

#/vis/viewer/set/viewpointVector -1 0 0
#/vis/viewer/addCutawayPlane 3.5 0 0 m -1 0 0
#/vis/drawVolume
#/vis/viewer/flush

#/vis/scene/add/trajectories
#/vis/filtering/trajectories/create/particleFilter
#/vis/filtering/trajectories/particleFilter-0/add mu+
#/vis/filtering/trajectories/particleFilter-0/add mu-l
#/vis/filtering/trajectories/particleFilter-0/add neutron

#/vis/scene/endOfEventAction accumulate
#/vis/viewer/set/autoRefresh true

# 
# 1000 events
#
#/tracking/verbose 0
#/run/verbose 0
#/event/verbose 0
#/run/beamOn 1000
