# This is a general macro for testing the neutron feature of the
# RICOCHET/REvOLT-0 Monte Carlo v0.1 (RMC)
#
# Adam Anderson
# adama@mit.edu
#

#/control/verbose 2
#/run/verbose 2
#/CDMS/verbose 3

# Configure detector (also defines subsequent commands)
#/CDMS/Lab MITReactor
/CDMS/Detector 100kg
#/CDMS/Detector shield
#/CDMS/Detector tower
/CDMS/Layout/Towers 1
/CDMS/UseShield
/CDMS/Source neutronwall
/CDMS/updateGeom

#/vis/open OGLIX
#/vis/verbose errors
#/vis/viewer/set/upVector 0 0 1
#/vis/viewer/set/viewpointThetaPhi 70 -10		# Slightly tilted
#/vis/viewer/addCutawayPlane 0 0 0 cm 1 0 0
#/vis/scene/add/trajectories [smooth] [rich]
#/vis/filtering/trajectories/create/particleFilter
#/vis/filtering/trajectories/particleFilter-0/add neutron
#/vis/drawVolume
#/vis/viewer/flush


/run/beamOn 3000
