# $Id: GNUmakefile,v 1.3 2010/10/29 04:56:25 kelsey Exp $
#
# --------------------------------------------------------------
# GNUmakefile for labs package    .  Dennis Wright  21 July 2010
# --------------------------------------------------------------

SKIPFILES := NoLabMessenger.cc

CPPFLAGS += -I$(G4BASE)/global/management/include \
            -I$(G4BASE)/global/HEPGeometry/include \
            -I$(G4BASE)/intercoms/include \
            -I$(G4BASE)/run/include \
            -I$(G4BASE)/geometry/management/include \
            -I$(G4BASE)/geometry/solids/CSG/include \
            -I$(G4BASE)/geometry/volumes/include \
            -I$(G4BASE)/materials/include \
            -I$(G4BASE)/graphics_reps/include

include build.gmk
